version: 1
status: candidate
source_system: SAP_HELP
source_type: SAP_STANDARD
module: MM

sources:
  - id: s4hana-2023-material-master
    product: SAP S/4HANA
    edition: on-premise
    version: "2023 Latest"
    language: en
    help_url: "https://help.sap.com/docs/SAP_S4HANA_ON-PREMISE/f7fddfe4caca43dd967ac4c9ce6a70e4/1eab9ca4-c056-42c6-a723-31a89c483118.html"
    repository: null
    branch: null
    commit_sha: null
    license: null
    status: candidate
    metadata_origin: source

  - id: s4hana-2025-goods-movement
    product: SAP S/4HANA
    edition: on-premise
    version: "2025 FPS01"
    language: en
    help_url: "https://help.sap.com/docs/SAP_S4HANA_ON-PREMISE/91b21005dded4984bcccf4a69ae1300c/742e46e570984d9aa74e468838f6e1ff.html"
    repository: null
    branch: null
    commit_sha: null
    license: null
    status: candidate
    metadata_origin: source
